// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-BR5qEQVagTo5CG6hvzWgFmlrcKiyd6A',
    appId: '1:1013147408557:web:b542f03224d28cea464e24',
    messagingSenderId: '1013147408557',
    projectId: 'contact-trace-3b-2023',
    authDomain: 'contact-trace-3b-2023.firebaseapp.com',
    storageBucket: 'contact-trace-3b-2023.appspot.com',
    measurementId: 'G-SV88MREYJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoTmxM71V2qUstIjtkzv89woiMiFp4y2k',
    appId: '1:1013147408557:android:05cb1c8445ac5e2e464e24',
    messagingSenderId: '1013147408557',
    projectId: 'contact-trace-3b-2023',
    storageBucket: 'contact-trace-3b-2023.appspot.com',
  );
}
